# Generated by Django 3.0.4 on 2020-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200303_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
